### ISSUE TITLE
Support for mouse-over popup hints? and multiline cues are getting chomped.

### ISSUE THREAD

**Issue by hojuruku** [e-lang/moodle-mod_elang#48]
I've just wrote an awk script that automatically converts youtube WEBVTT subtitle files for use with mod_elang, with defining words for students to guess done automatically based on the word's size. Words are not given more than once per student per course, it maintains a word-list. Short subtitle lines can be joined. It will soon have external dictionary support, phrase detection, automatic moodle glossary builder, and whatever else I can think of. Oh and of course instructions for people to combine it with ffmpeg, ffmpegthumbailer, youtube-dl, cygwin (for windows people), to rapidly author video appreciation courses with mod_elang on the moodle forums.

Presently it resolves a bug in mod_elang where there are multiline srt/webvtt cues that get chomped. I'll share the draft script here ASAP.

This ticket is a feature request.

```
if ($text[0] == '[' && $text[strlen($text) - 1] == ']')
                                                {
                                                        $data[] = array('type' => 'input', 'content' => substr($text, 1, strlen($text) - 2), 'order' => $i++, 'help' => true);
                                                }
                                                elseif ($text[0] == '{' && $text[strlen($text) - 1] == '}')
                                                {
                                                        $data[] = array('type' => 'input', 'content' => substr($text, 1, strlen($text) - 2), 'order' => $i++, 'help' => false);
                                                }
```

I'd like you to exend this to include a new kind of bracket, perhaps a {} inside a [] that allows a popup hint. If defined the use is presented with a definition instead of the word, or they can click the i box again if they give up.

As your code doesn't support multiline cues, you'd have to fix that first or demand that non printable characters such as newline be embedded in the string using backslash escape characters (e.g. "\n").

i.e.
WEBVTT
metadata: tag

cue-1
hh:mm:ss.frac -> hh:mm:ss.frac timestamp options
here is some text {that} is displayed in mod_elang
the text on this line has gone into the void - not displayed
(\n - a empty line - new record)

Please see the next ticket for my draft awk script for how I fixed this, and my idea for possibly including a similar algorithm in PHP to allow only a youtube url and some settings for instantly setting up a mod_elang video.

**Comment by chdemko** [comment]
The current code supports now multiline cues. Second part of the issue (Support for mouse-over popup hints) is not yet present.
