### ISSUE TITLE
Support for Non-UTF-8 encoded subtitle files

### ISSUE THREAD

**Issue by ralferlebach** [e-lang/moodle-mod_elang#55]
As I am seeing forward to a Moodle workshop for foreign language teachers, students and colleagues, I now think that I also should put considerably a focus on elang. (Now, as I finally got it running. ^^)

One major drawback in user friendlyness is for sure the fact, that one has to convert his/her subtitles into UTF-8 encoding before uploading. Basically spoken: It would take me a lot of time and efforts to explain and train that. (They have to install another text editor etc. etc.)

Not converting the file will and in a crash with an error message that is not readable by normal users. ;-)

I drived into the current code and coded a solution basing on mb-convert_encoding and mb_detect_encoding with the STRICT paradigm. Also a workaround for UTF-16 and UTF-32. 
Works fine so far.

However, as it seems, there are some structural changes in lib.php and locallib.php. Will these changes already cope with this problem or should I propose the code fragment (or fork it and put it untested in the code)

Ralf

**Comment by chdemko** [comment]
The best way is to propose a pull request from your fork.

**Comment by ralferlebach** [comment]
OK. I try to do so today evening. ;-)

**Comment by ralferlebach** [comment]
https://github.com/e-lang/moodle-mod_elang/pull/56

This is the code fragment I ended with in my locallib.php of the version 1.0 

Would be great when it appears in version 1.1.0 (and maybe also in the release candidate for testing). At the moment I cannot do more as locallib.php seems not up to date, it will have to be integrated there.

**Comment by ralferlebach** [comment]
Already tested the code with various encodings in the 1.0 version. There are some known issues with UTF 16 and 32. The encodings are detected correctly, the converted strings also looks good however it does not appear in the player (or even worse, it stops the player working).

Most other usually used encodings (ISO-8859-x, JIS etc.) work just fine and smooth though as far as I tested. I will keep track of this issue and provide necessary code changes in the repo as soon as I can test it in the release candidate
