### ISSUE TITLE
Student view of RC1-1.1.0 crashes with all kind of subtitles

### ISSUE THREAD

**Issue by ralferlebach** [e-lang/moodle-mod_elang#57]
I was just testing the RC1 1.1.0 and the student view crashes when any kind of cues are given.

What I could check so far:
* The subtitle file was in UTF-8 encoding.
* The cues are stored in the DB correctly.
* Checked the language string changes in the js-files again against any ill-spellings etc.
* The response from server.php looks good:
{"title":"Test: Listening Landscape","description":"<p>Lass uns gehen!<\/p><p><\/p>","total":0,"success"
:0,"error":0,"help":0,"cues":[{"number":0,"id":"1205","title":"Wei\u00df du, wie die Dichter schreiben
,","begin":6.086,"end":9.481,"elements":[{"type":"text","content":"Wei\u00df du, wie die Dichter schreiben
,"}],"remaining":0},{"number":1,"id":"1206","title":"hast du je einen gesehen?","begin":9.482,"end":12
.505,"elements":[{"type":"text","content":"hast du je einen gesehen?"}],"remaining":0},{"number":2,"id"
:"1207","title":"Dichter schreiben einsam.","begin":12.506,"end":15.622,"elements":[{"type":"text","content"
:"Dichter schreiben einsam."}],"remaining":0},{"number":3,"id":"1208","title":"Und wei\u00df du, wie
 die Maler malen,","begin":15.623,"end":33.6,"elements":[{"type":"text","content":"Und wei\u00df du,
 wie die Maler malen,"}],"remaining":0}],"limit":"10","sources":[{"src":"http:\/\/localhost\/moodle29
\/pluginfile.php\/61\/mod_elang\/videos\/Revolverheld%20-%20Lass%20Uns%20Gehen.mp4","type":"video\/mp4"
}],"poster":"","track":"http:\/\/localhost\/moodle29\/pluginfile.php\/61\/mod_elang\/subtitle\/Christina
%20St%C3%BCrmer%20-%20Engel%20fliegen%20einsam.utf8%20with%20BOM.vtt","pdf":"http:\/\/localhost\/moodle29
\/pluginfile.php\/61\/mod_elang\/pdf\/Christina%20St%C3%BCrmer%20-%20Engel%20fliegen%20einsam.utf8%20with
%20BOM.pdf","language":"de-DE"}
* BugZilla reports reads:
apps.js (line 36, colum 518)
RangeError: Total value "1" is incorrect
...al){var n=this.total;throw this.total=t,new RangeError('Total value "'+n+'" is i...
* If subtitle cues are deleted from DB, the video appears again - so seems to be a problem
![error rc1-1 1 0 given utf-8 subtitles](https://cloud.githubusercontent.com/assets/12737344/8145363/5b370b5a-1205-11e5-96d1-f0b2880e0262.png)
![error rc1-1 1 0 no subtitles in db](https://cloud.githubusercontent.com/assets/12737344/8145364/5b3a425c-1205-11e5-9191-7ccfd5bd40ae.png)
* Trying to access the internal vtt file is successful, trying to access the generated PDF fails with a 500 internal server error

**Comment by chdemko** [comment]
Could. You sens me thé files or a link to download them chdemko at gmail dot com

**Comment by ralferlebach** [comment]
It's strange: The demo videos on your site are still working, even the German ones with Umlauts. However, when I try to bring my own video and subtitle online, it crashes again.

**Comment by chdemko** [comment]
Could you send me the files or a link to download them at chdemko at gmail dot com

**Comment by ralferlebach** [comment]
Great, it's working in RC2.
